import { SectionHeader } from "@/components/shared/SectionHeader";

const POINTS = [
  {
    title: "Your principal stays yours",
    body: "Deposits are tracked per-wallet and accounted for separately from prize funds — withdraw your tracked principal whenever the production contracts allow it.",
  },
  {
    title: "Yield funds the prize, never principal",
    body: "Only realized yield generated by the pooled deposits can ever fund a round's prize. Principal accounting and prize accounting never mix.",
  },
  {
    title: "Eligible savers enter every round",
    body: "Depositors are automatically eligible for recurring draws while their funds are in the vault — no separate ticket purchase or lockup required.",
  },
];

export function SaveWinExplainer() {
  return (
    <div className="flex flex-col gap-10">
      <SectionHeader
        eyebrow="Save & Win"
        title="Pooled savings, personal principal, shared upside"
        description="YieldJack turns the yield generated by pooled deposits into recurring prizes for eligible savers — without touching what each saver put in."
      />
      <div className="grid gap-6 sm:grid-cols-3">
        {POINTS.map((point) => (
          <div key={point.title} className="rounded-xl border border-border bg-surface p-5">
            <h3 className="text-base font-semibold text-foreground">{point.title}</h3>
            <p className="mt-2 text-sm text-muted">{point.body}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
