export function RiskNotice() {
  return (
    <div className="rounded-xl border border-gold/40 bg-gold/5 p-6">
      <h3 className="text-sm font-semibold text-gold">Testnet risk notice</h3>
      <ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-muted">
        <li>Everything on this page uses worthless Mock USDG and Mock JACK — no real value.</li>
        <li>Contracts are unaudited and explicitly not intended for mainnet use.</li>
        <li>Yield is simulated on-chain, not generated by a real money-market integration.</li>
        <li>Randomness is demo-grade (block-derived) — insecure by design, for demonstration only.</li>
        <li>Deposits are capped and the participant list is capped at 256 wallets.</li>
      </ul>
    </div>
  );
}
