#!/usr/bin/env node
// Extracts compiled contract ABIs from Foundry's `out/` directory into a single TypeScript
// module the web app and keeper both import. Run via `pnpm sync:abis` after `forge build`.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");
const outDir = path.join(repoRoot, "packages/contracts/out");
const targetFile = path.join(repoRoot, "packages/config/src/abis.ts");

const CONTRACTS = [
  { name: "MockUSDG", artifact: "MockUSDG.sol/MockUSDG.json" },
  { name: "MockJACK", artifact: "MockJACK.sol/MockJACK.json" },
  { name: "MockYieldSource", artifact: "MockYieldSource.sol/MockYieldSource.json" },
  { name: "DemoRandomnessProvider", artifact: "DemoRandomnessProvider.sol/DemoRandomnessProvider.json" },
  { name: "YieldJackVault", artifact: "YieldJackVault.sol/YieldJackVault.json" },
  { name: "DemoPrizeEngine", artifact: "DemoPrizeEngine.sol/DemoPrizeEngine.json" },
  { name: "SponsorRegistry", artifact: "SponsorRegistry.sol/SponsorRegistry.json" },
];

if (!existsSync(outDir)) {
  console.error(
    `error: ${outDir} does not exist. Run \`pnpm contracts:build\` first, then \`pnpm sync:abis\`.`,
  );
  process.exit(1);
}

const entries = CONTRACTS.map(({ name, artifact }) => {
  const artifactPath = path.join(outDir, artifact);
  if (!existsSync(artifactPath)) {
    console.error(`error: missing build artifact for ${name} at ${artifactPath}`);
    process.exit(1);
  }
  const json = JSON.parse(readFileSync(artifactPath, "utf8"));
  return { name, abi: json.abi };
});

const header = `// AUTO-GENERATED by scripts/sync-abis.mjs — do not edit by hand.
// Regenerate with \`pnpm contracts:build && pnpm sync:abis\`.
`;

const body = entries
  .map(({ name, abi }) => `export const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;`)
  .join("\n\n");

writeFileSync(targetFile, `${header}\n${body}\n`);
console.log(`Wrote ${entries.length} ABIs to ${path.relative(repoRoot, targetFile)}`);
